// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVEsylQkSq4Llxa64wwcARG-MdBRtXl5M',
    appId: '1:656443622139:web:7f346ef5f1e6bfbc6fa65e',
    messagingSenderId: '656443622139',
    projectId: 'book-it-up-53786',
    authDomain: 'book-it-up-53786.firebaseapp.com',
    storageBucket: 'book-it-up-53786.firebasestorage.com',
    measurementId: 'G-CFKZ4HRFS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQNnkp9GkxnQ3YsMq5x_y-ahu8ATAG8KA',
    appId: '1:656443622139:android:b27243b287be8ce46fa65e',
    messagingSenderId: '656443622139',
    projectId: 'book-it-up-53786',
    storageBucket: 'book-it-up-53786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_6Kg3pvhgn6d_L_Woth2Zl2ANCQvPfjk',
    appId: '1:656443622139:ios:188fa6ea8bb2b9426fa65e',
    messagingSenderId: '656443622139',
    projectId: 'book-it-up-53786',
    storageBucket: 'book-it-up-53786.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_6Kg3pvhgn6d_L_Woth2Zl2ANCQvPfjk',
    appId: '1:656443622139:ios:188fa6ea8bb2b9426fa65e',
    messagingSenderId: '656443622139',
    projectId: 'book-it-up-53786',
    storageBucket: 'book-it-up-53786.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVEsylQkSq4Llxa64wwcARG-MdBRtXl5M',
    appId: '1:656443622139:web:3a10a16e0bdb60856fa65e',
    messagingSenderId: '656443622139',
    projectId: 'book-it-up-53786',
    authDomain: 'book-it-up-53786.firebaseapp.com',
    storageBucket: 'book-it-up-53786.firebasestorage.app',
    measurementId: 'G-E52V34ZP0E',
  );

}